"""
SENTINEL — AI Generation Detection Agent (AIGA)

Detects signs that a response was generated by an AI rather than
spoken spontaneously by a human candidate.

Signals:
  - Low burstiness (uniform sentence lengths)
  - Absence of hedge language
  - Lack of temporal anchors (personal experience references)
  - Structural perfection (enumerated lists)
"""

import re
from dataclasses import dataclass

try:
    import spacy
    try:
        _nlp = spacy.load("en_core_web_sm")
    except OSError:
        _nlp = None
except ImportError:
    spacy = None
    _nlp = None

from sentinel.config import AIGA_BURSTINESS_RED, AIGA_HEDGE_RATIO_RED


# Hedge lexicon — phrases that indicate genuine human uncertainty
HEDGE_LEXICON = [
    "i think", "i believe", "kind of", "sort of", "in my experience",
    "i'm not sure", "maybe", "probably", "usually", "roughly",
    "i guess", "from what i recall", "if i remember correctly",
]

# Temporal anchor pattern — first-person past-tense project narratives
TEMPORAL_ANCHOR_PATTERN = re.compile(
    r"\b(I|we)\s+(built|deployed|debugged|worked on|shipped|broke|fixed|"
    r"learned|struggled|optimised|optimized|owned|led|designed|refactored)\b",
    re.IGNORECASE,
)

# Enumerated list pattern
ENUM_LIST_PATTERN = re.compile(r"^\d+\.\s", re.MULTILINE)

# Bullet point pattern
BULLET_PATTERN = re.compile(r"^[\-\*\•]\s", re.MULTILINE)


@dataclass
class AIGAResult:
    """Output of the AI Generation Detection Agent."""
    signal: str
    burstiness_score: float
    hedge_ratio: float
    temporal_anchor_found: bool
    note: str


class AIGenerationDetectionAgent:
    """
    Analyses response text for statistical signatures of AI generation.
    """

    def analyse(self, response: str) -> AIGAResult:
        """
        Analyse a single response for AI generation signals.

        Args:
            response: The candidate's response text.

        Returns:
            AIGAResult with signal and analysis data.
        """
        try:
            if not response or len(response.split()) < 10:
                return AIGAResult(
                    signal="GREEN",
                    burstiness_score=1.0,
                    hedge_ratio=0.0,
                    temporal_anchor_found=False,
                    note="Response too short for AI detection analysis.",
                )

            signals = []
            notes = []

            # ─── 1. Burstiness ───────────────────────────────────
            sentences = self._get_sentences(response)
            burstiness_score = self._compute_burstiness(sentences)

            if burstiness_score < AIGA_BURSTINESS_RED:
                signals.append("RED")
                notes.append(f"burstiness {burstiness_score:.3f} (below RED threshold)")
            elif burstiness_score < AIGA_BURSTINESS_RED * 2:
                signals.append("AMBER")
                notes.append(f"burstiness {burstiness_score:.3f} (below AMBER threshold)")

            # ─── 2. Hedge ratio ──────────────────────────────────
            hedge_ratio = self._compute_hedge_ratio(response)

            if hedge_ratio < AIGA_HEDGE_RATIO_RED:
                signals.append("RED")
                notes.append(f"hedge ratio {hedge_ratio:.4f} (below threshold)")
            # Note: ECA multiplier is NOT applied — absence of hedging is
            # experience-level-independent as a signal.

            # ─── 3. Temporal anchors ─────────────────────────────
            temporal_anchor_found = bool(TEMPORAL_ANCHOR_PATTERN.search(response))

            if (not temporal_anchor_found
                    and "RED" in signals
                    and hedge_ratio < AIGA_HEDGE_RATIO_RED):
                # Compound signal: no personal anchors + low burstiness + no hedging
                notes.append("no temporal anchors with compound AI signals")

            # ─── 4. Structural perfection ────────────────────────
            enum_count = len(ENUM_LIST_PATTERN.findall(response))
            bullet_count = len(BULLET_PATTERN.findall(response))
            total_list_items = enum_count + bullet_count

            if total_list_items >= 3:
                signals.append("AMBER")
                notes.append(
                    f"{total_list_items} structured list items "
                    f"(unusual for spoken responses)"
                )

            # ─── Final signal ────────────────────────────────────
            signal_priority = {"RED": 2, "AMBER": 1, "GREEN": 0}
            signal = max(
                signals if signals else ["GREEN"],
                key=lambda s: signal_priority.get(s, 0),
            )

            if not notes:
                note = "No AI generation signals detected."
            else:
                note = "AI signals: " + "; ".join(notes) + "."

            return AIGAResult(
                signal=signal,
                burstiness_score=round(burstiness_score, 4),
                hedge_ratio=round(hedge_ratio, 4),
                temporal_anchor_found=temporal_anchor_found,
                note=note,
            )

        except Exception as e:
            return AIGAResult(
                signal="GREEN",
                burstiness_score=1.0,
                hedge_ratio=0.0,
                temporal_anchor_found=False,
                note=f"parse error — insufficient signal. ({str(e)})",
            )

    @staticmethod
    def _get_sentences(text: str) -> list[str]:
        """Split text into sentences using spaCy or fallback regex."""
        if _nlp is not None:
            try:
                doc = _nlp(text)
                return [sent.text.strip() for sent in doc.sents if sent.text.strip()]
            except Exception:
                pass
        # Fallback: simple sentence splitting
        return [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]

    @staticmethod
    def _compute_burstiness(sentences: list[str]) -> float:
        """
        Compute burstiness as variance of sentence lengths normalised by mean.
        Low burstiness = uniform = suspicious.
        """
        if len(sentences) < 2:
            return 1.0  # Not enough data, assume OK

        lengths = [len(s.split()) for s in sentences]
        mean_len = sum(lengths) / len(lengths)
        variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
        return variance / (mean_len + 1e-6)

    @staticmethod
    def _compute_hedge_ratio(text: str) -> float:
        """Compute the ratio of hedge tokens to total words."""
        text_lower = text.lower()
        total_words = len(text_lower.split())
        if total_words == 0:
            return 0.0

        hedge_count = 0
        for hedge in HEDGE_LEXICON:
            hedge_count += text_lower.count(hedge)

        return hedge_count / total_words
